# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "42d18ab94654c48ad51d381269a89bcc"
name = "Aervo"
application_url = application_url = "https://api.aervoapp.com/auth/shopify"

embedded = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://api.aervoapp.com/webhooks/shopify/customers_data_request"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://api.aervoapp.com/auth/shopify/callback" ]
