-- ============================================================
-- Aervo Smart Playbooks — DB Migration
-- Run this in pgAdmin4 Query Tool
-- ============================================================

-- 1. playbooks
--    One row per triggered playbook per user.
--    status: 'active' | 'completed' | 'dismissed'
--    trigger_type maps to the 6 detection conditions.

CREATE TABLE IF NOT EXISTS playbooks (
  id               SERIAL PRIMARY KEY,
  user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  trigger_type     VARCHAR(50) NOT NULL,
    -- 'revenue_down' | 'stockout_imminent' | 'repeat_rate_dropping'
    -- 'vip_customers_quiet' | 'revenue_spike' | 'conversion_falling'
  title            VARCHAR(255) NOT NULL,
  status           VARCHAR(20) NOT NULL DEFAULT 'active',
  priority         INTEGER NOT NULL DEFAULT 0,
    -- higher = more urgent, used for sort order
  context_snapshot JSONB,
    -- snapshot of the store data that triggered this playbook
    -- e.g. { "revenue_change_pct": -14, "period": "7d", "top_products": [...] }
  integration      VARCHAR(20) NOT NULL DEFAULT 'shopify',
    -- 'shopify' | 'square'
  triggered_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at     TIMESTAMPTZ,
  dismissed_at     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. playbook_steps
--    Each playbook has 4-6 ordered steps generated by Claude.
--    Steps are generated once and cached — not regenerated on each load.

CREATE TABLE IF NOT EXISTS playbook_steps (
  id           SERIAL PRIMARY KEY,
  playbook_id  INTEGER NOT NULL REFERENCES playbooks(id) ON DELETE CASCADE,
  step_number  INTEGER NOT NULL,
  title        VARCHAR(255) NOT NULL,
  description  TEXT NOT NULL,
  context_tip  TEXT,
    -- the purple "from your store data" callout, specific to this step
  is_complete  BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_playbooks_user_id
  ON playbooks(user_id);

CREATE INDEX IF NOT EXISTS idx_playbooks_user_status
  ON playbooks(user_id, status);

CREATE INDEX IF NOT EXISTS idx_playbook_steps_playbook_id
  ON playbook_steps(playbook_id);

-- ============================================================
-- Auto-update updated_at on playbooks
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_playbooks_updated_at ON playbooks;
CREATE TRIGGER set_playbooks_updated_at
  BEFORE UPDATE ON playbooks
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- Done. Verify with:
--   SELECT * FROM playbooks LIMIT 5;
--   SELECT * FROM playbook_steps LIMIT 5;
-- ============================================================