const PLANS = {
  free: {
    name: "Starter",
    integrations: 1,
    dataHistoryDays: 7,
    aiMessagesPerMonth: 3,
    fullDashboard: false,
    googleReviews: false,
    customerSegmentation: false,
    revenueForecast: false,
    winBackCampaigns: false,
    aiMarketingCopy: false,
    whiteLabel: false,
    competitorBenchmarking: false,
    maxLocations: 1,
  },
  essential: {
    name: "Essential",
    integrations: 1,
    dataHistoryDays: 90,
    aiMessagesPerMonth: Infinity,
    fullDashboard: true,
    googleReviews: 50,
    customerSegmentation: true,
    revenueForecast: false,
    winBackCampaigns: false,
    aiMarketingCopy: false,
    whiteLabel: false,
    competitorBenchmarking: false,
    maxLocations: 1,
  },
  pro: {
    name: "Pro",
    integrations: 2,
    dataHistoryDays: 730,
    aiMessagesPerMonth: Infinity,
    fullDashboard: true,
    googleReviews: Infinity,
    customerSegmentation: true,
    revenueForecast: true,
    winBackCampaigns: true,
    aiMarketingCopy: true,
    whiteLabel: false,
    competitorBenchmarking: false,
    maxLocations: 2,
  },
  business: {
    name: "Business",
    integrations: 5,
    dataHistoryDays: Infinity,
    aiMessagesPerMonth: Infinity,
    fullDashboard: true,
    googleReviews: Infinity,
    customerSegmentation: true,
    revenueForecast: true,
    winBackCampaigns: true,
    aiMarketingCopy: true,
    whiteLabel: true,
    competitorBenchmarking: true,
    maxLocations: 5,
  },
};

module.exports = PLANS;